import Head from "next/head";
import assets from "../assets";
import styles from "../styles/Home.module.css";
import { Download, Features, Sectionwrapper } from "../components";

export default function Home() {
  //console.log("moc = ",assets.homeHero.src)
  return (
    <>
      <Head>
        <title>NFT MarketPlace App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sectionwrapper
        title="Your own store of NFTs. Start Selling and Growing"
        description="Buy, Store, Collect NFTs and Earn crypto. Join 10 Million+ people using NFT MarketPlace App."
        showBtn
        mockupImg={assets.homeHero.src}
        banner="banner"
      />

      <Sectionwrapper
        title="Smart User Interface MarketPlace"
        description="Experience a buttery UI of Mohit NFT MarketPlace. Smooth constant color of a fluent UI design."
        mockupImg={assets.homeCards.src}
        reverse
      />

      <Features />
    </>
  );
}
